# Generated by Django 4.0.7 on 2022-09-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestionDocumental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='forma',
        ),
    ]
