# Generated by Django 4.0.7 on 2022-09-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaGestionDocumental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
